export default function HomePage() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-8">
      <div className="game-card max-w-4xl text-center">
        <h1 className="mb-6 text-6xl font-bold text-gradient">
          TrivAI
        </h1>
        <p className="mb-8 text-xl text-gray-300">
          Experience the future of gaming with AI-powered multiplayer trivia
        </p>
        
        <div className="mb-12 grid gap-6 md:grid-cols-3">
          <div className="player-card">
            <div className="mb-3 text-4xl">🤖</div>
            <h3 className="mb-2 text-lg font-semibold">AI-Powered</h3>
            <p className="text-sm text-gray-400">
              Questions generated by advanced Large Language Models
            </p>
          </div>
          
          <div className="player-card">
            <div className="mb-3 text-4xl">👥</div>
            <h3 className="mb-2 text-lg font-semibold">Multiplayer</h3>
            <p className="text-sm text-gray-400">
              Compete with 2-4 players in real-time trivia battles
            </p>
          </div>
          
          <div className="player-card">
            <div className="mb-3 text-4xl">🏆</div>
            <h3 className="mb-2 text-lg font-semibold">Competitive</h3>
            <p className="text-sm text-gray-400">
              Progressive scoring with bonus rounds and multipliers
            </p>
          </div>
        </div>

        <div className="flex flex-col gap-4 sm:flex-row sm:justify-center">
          <button className="btn btn-primary text-lg">
            Start Playing
          </button>
          <button className="btn btn-secondary text-lg">
            Join Game
          </button>
        </div>

        <div className="mt-12 text-sm text-gray-500">
          <p>
            Built by{' '}
            <span className="text-primary-blue">Jamie Matthew van der Pijll</span>
          </p>
          <p className="mt-2">
            Open source • AI-driven • Gaming platform
          </p>
        </div>
      </div>
    </main>
  );
} 